linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unconvert
    - gosec
    - misspell
    - unparam
    - whitespace
    - goconst
    - gocyclo
    - dupl
    - gocritic
    - godot
    - goimports
    - revive
    - stylecheck
    - unused
    - varcheck

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
  stylecheck:
    checks:
      - all
      - ST1000
      - ST1003
      - ST1016
      - ST1020
      - ST1021
      - ST1022
      - ST1023

run:
  deadline: 5m
  skip-dirs:
    - vendor
  skip-files:
    - ".*_test.go$"

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gocyclo
        - gosec
        - goconst
        - gocritic
        - stylecheck
        - varcheck
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  new-from-rev: ""
  new-from-patch: ""
  fix: false 